from itertools import combinations
from sage.all import matrix

# ======================================================================================
#
# Divided powers of even-degree elements of Lambda V, in char 2.
#
# Sage has no divided-power algebra, and we do not need one: the attack only uses the
# 2-power tower q^{(2^j)}, and that tower is generated by iterating the DIVIDED SQUARE.
#
# Divided-power identity:   (x^{(a)})^{(b)} = ((ab)! / (a!^b b!)) x^{(ab)}
# With a = 2^j, b = 2:      (x^{(2^j)})^{(2)} = (1/2) C(2^{j+1}, 2^j) x^{(2^{j+1})}
# By Kummer C(2^{j+1}, 2^j) = 2 mod 4, so (1/2) C(2^{j+1}, 2^j) is ODD (3, 35, 6435, ...)
# hence == 1 in char 2.  Therefore, EXACTLY (not approximately), in char 2:
#
#                      q^{(2^{j+1})} = ( q^{(2^j)} )^{(2)}
#
# The divided square itself needs no lifting to Z.  For x = sum_S c_S e_S of even degree,
# x /\ x has no S = T terms, and each unordered disjoint pair {S, T} is hit twice with the
# same sign (even-degree elements commute), so halving over Z leaves
#
#            x^{(2)} = sum over unordered disjoint pairs {S, T}  c_S c_T e_{S u T}
#
# which is pure base-field arithmetic.  Signs are all +1 (char 2), matching the
# conventions in multilinear_algebra.py.
#
# Elements of Lambda^e V are dicts { tuple(sorted(indices)) : coefficient }.
#
# ======================================================================================

def alternating_form(f):
    """n x n matrix -> the polar/alternating 2-vector f + f^T as an element of Lambda^2 V."""
    n = f.nrows()
    q = {}
    for x in range(n):
        for y in range(x + 1, n):
            c = f[x, y] + f[y, x]
            if c: q[(x, y)] = c
    return q


def divided_square(x):
    """x^{(2)} for x of even degree: sum over unordered disjoint pairs of its support."""
    items = list(x.items())
    res = {}
    for i in range(len(items)):
        S, cS = items[i]
        setS = set(S)
        for j in range(i + 1, len(items)):
            T, cT = items[j]
            if setS & set(T): continue
            mon = tuple(sorted(setS | set(T)))
            res[mon] = res.get(mon, 0) + cS * cT
    return {mon: c for mon, c in res.items() if c}


def divided_power_tower(q, maxdeg):
    """[(2, q), (4, q^{(2)}), (8, q^{(4)}), ...], all generators of degree <= maxdeg.

    Uses q^{(2^{j+1})} = (q^{(2^j)})^{(2)}, valid in char 2 (see header)."""
    tower = []
    deg, cur = 2, dict(q)
    while deg <= maxdeg and cur:
        tower.append((deg, cur))
        if 2 * deg > maxdeg: break          # don't pay for a square we would discard
        cur = divided_square(cur)
        deg *= 2
    return tower


def tower_generators(fs, maxdeg):
    """The full generating set { q_i^{(2^j)} } of the divided-power ideal, as (degree, elt)."""
    return [g for f in fs for g in divided_power_tower(alternating_form(f), maxdeg)]


def multiplication_matrix(n, d, gens, k):
    r"""
        m_gens: (+)_g Lambda^{d - deg g} V -> Lambda^d V,   columns  g /\ e_J

    The image is the degree-d part I_d of the divided-power ideal.  The attack's solution
    space is the annihilator of I_d, i.e. the LEFT null space of this matrix; it contains
    the Plucker coordinates of Lambda^d O for any totally isotropic O.
    """
    basis = list(combinations(range(n), d))
    idx = {b: i for i, b in enumerate(basis)}

    entries = {}
    col = 0
    for deg, g in gens:
        if deg > d: continue
        for J in combinations(range(n), d - deg):
            sJ = set(J)
            hit = False
            for mon, c in g.items():
                if sJ & set(mon): continue
                r = idx[tuple(sorted(sJ | set(mon)))]
                entries[(r, col)] = entries.get((r, col), 0) + c
                hit = True
            if hit: col += 1

    # DENSE on purpose: matrix(k, r, c, dict) would build a sparse matrix, and Sage's
    # sparse echelon over GF(2^e) is orders of magnitude slower than M4RIE dense
    # (48s vs well under 1s for a 495 x 536 rank over GF(16)).
    return matrix(k, len(basis), col, entries, sparse=False)


def plucker_rows(A, d):
    """Basis of Lambda^d O as Plucker coordinate vectors, O = column span of the n x o A.

    Row T (a d-subset of the o columns), column S (a d-subset of the n rows): det A[S, T]."""
    k, n, o = A.base_ring(), A.nrows(), A.ncols()
    rows = list(combinations(range(o), d))
    cols = list(combinations(range(n), d))
    return matrix(k, len(rows), len(cols),
                  [[A.matrix_from_rows_and_columns(list(S), list(T)).det() for S in cols]
                   for T in rows])


def recover_subspace(sols, n, d):
    """Recover O from a basis of Lambda^d O given as Plucker coordinate vectors.

    Contracting Lambda^d O by Lambda^{d-1} V* lands in O and spans it: for a solution
    omega and a (d-1)-subset J, the vector v with v_i = omega_{J u {i}} lies in O."""
    k = sols.base_ring()
    cols = {S: j for j, S in enumerate(combinations(range(n), d))}
    vecs = []
    for r in range(sols.nrows()):
        w = sols.row(r)
        for J in combinations(range(n), d - 1):
            sJ = set(J)
            v = [0] * n
            nz = False
            for i in range(n):
                if i in sJ: continue
                c = w[cols[tuple(sorted(sJ | {i}))]]
                if c: v[i] = c; nz = True
            if nz: vecs.append(v)
    if not vecs: return matrix(k, 0, n)
    return matrix(k, vecs).row_space().basis_matrix()
